homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret my_latitude
  longitude: !secret my_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 49
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret hass_ui_pwd

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  platform: yr

logger:
#  default: info
#  logs:
#    homeassistant.components.mqtt: debug

# Text to speech
tts:
  platform: google

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

mqtt:
  broker: 127.0.0.1
#  client_id: mygateway1 

light:
  - platform: lifx

mysensors:
  gateways:
    - device: mqtt
      topic_in_prefix: 'mygateway1-out'
      topic_out_prefix: 'mygateway1-in'

switch:
  - platform: tplink
    host: !secret garage_light_ip

device_tracker:
  - platform: netgear
    host: !secret netgear_ip
    username: !secret netgear_username
    password: !secret netgear_password

group: !include groups.yaml
automation: !include automations.yaml
